#+TITLE: Adventure on Planet X
#+AUTHOR Rill
#+DESCRIPTION: A Star Runner and Ronnie Camberwell Adventure
It was a dark and stormy night.

Christabel objects.

"This is a trite opening," she says.

I am annoyed.

"It was a dark and stormy night on Planet X," I say.
When Detective Ronnie Camberwell and I first arrived at the Mountain View Hotel, it was a pleasant day.  The desk clerk gave us a choice of rooms.  Ronnie chose a suite that provided an obstructed view of the mountains.  "After all," she said, "that is why we came--to look at the mountains."

I did not come to look at mountains, but I did not say anything.  Ronnie had suggested our trip.  She wanted to spend time outside her comfort zone, as she called it, with outdoor spaces in planet atmosphere.  I know I do not like such environments.  I am a
 creature of space vehicles and space stations.  I like overheads and walls not too far away.  I am content to breathe recycled air and to limit my exposure to living things.

Ronnie, too, had grown up in a controlled environment.  She lived under the dome covering Ptolemy City.  With our relocation to Half Moon Bay Station, she was feeling a bit claustrophobic.  She missed the views she had across the city and through the dome 
to the lurid skies of her home planet Hypatia.

I accompanied Ronnie so that we could have time together before work commitments separated for some time.
Detective Ronnie Camberwell and I had decided to take a vacation at the Mountain View Hotel.Our suite possessed a balcony.  Ronnie stepped through the French doors and leaned against the railing.

"Be careful," I said, padding to the doorway.  "You could fall."

"The balcony is high enough, Star."  Ronnie turned to assure me she was all right.  "I am trying to get used to open places when we go planet side.  Besides, I have never been outside during a storm.  I thought it would be an interesting experience."

I shuddered.  Already a few raindrops were falling.  Several fell on my face.  I shook my head and retreated into the lounge.
