
* 1. Interdiction
    - The newscast announces the border closings.
    - Captain Star Runner is introduced.
    - Star is uncomfortable with the anti-Pantheran sentiment in the lounge.
    - A spacer comments to Star that Star is not included in the general anti-Pantheran sentiment.

** Conflicts
    1.  Coalition and its frontiers.
    2. Pantherans and humans.
    3. Captain Star Runner, the Pantheran, operating in human-controlled space as an independent operator.

* 2. Star Becomes An Outsider
    - Just outside the lounge, Star is accosted by spacers new to Dirty World Station.  They think Star is a Pantheran spy.
    - The scuffle summons spacers from the lounge who side with Star.
    - Even so, Star senses the new spacers have sown seeds of doubt in the formerly friendly spacers.
    - Langley tells Star that it is no longer welcome in the lounge.
** Conflicts
    - Physical conflict between Star and the new spacers
    - emotional conflict between Star and the spacers in the lounge.
    - Langley tells Star that it is no longer welcome at the lounge.
* 3. Secret Procurement
    - Star receives an anonymous request for unusual items.
    - Star works off-station.
    - After picking up the various objects, Star travels to Pirate Cove.


* 4. Arrival at Pirate's Cove
    - Star meets Station Manager Prudence Wu who invites Star to a conference.
    - Star gets something to eat at the Spyglass Cafe.
    - Star meets Tamara.
    - Star is exposed to the wonders of human food.

** Conflicts
    - mysteriousness of being invited to a conference
    - interacting one on one with Tamara.  Tamara is more interested than threatened by Star.  Star does not know what to make of this.
* 5. The Proposal
(The outline here needs to be more complete.)
    - Star meets its first Fungusan.
    - Star is told of the military action to steal a Pantheran warship.
    - Star agrees to help for the right price.
** Conflicts
    - Star is uneasy at the telepathic connection to the Fungusian.
    - The humans are uneasy about employing a Pantheran but they have no alternative.
    - Star is afraid proximity to the border and the Pantheran military will result in its capture and death.
    - Star's desire for profit overcomes its reluctance.  Why does Star have this overwhelming desire for profit?  It may be that Star's precarious position in society means Star has to provide for itself against lean times with so much suspicion about whose side it is on.
 
