#+Title  The Essential Journey to Bethlehem
#+AUTHOR  Rill
#+EMAIL  rill*at*rillonline.me
#+OPTIONS: num:nil
* About This Page
November 30 begins Advent in the Christian church.  Some churches focus on Advent while others may only give it passing notice.  I have decided to focus on Advent this year for three reasons:
1.  I am editing an Advent devotional I wrote in 2006.  I hope to post one devotional per day.  You can read it on this blog as well as what I write here.
2.  I will not be at church on the first Sunday of Advent.  I need to take responsibility for my own spiritual journey.
3.  I want to make prayer, Bible reading and reflection and writing about Scripture part of my daily life.
I went in search of a list of daily readings.  The [[http://scriptureunion.org/][Scripture Union/USA]] was one of the web sites I found.  They have a 14-page booklet with a reading guide, prayers, reflection questions and an application section.  I thought it would be a very structured way to go about my own devotions and record them here.  I hope they are useful to both me and you.
* Day 1 (November 30, 2013)
**  Pray
God, you have promised a *paraclete*, one who walks beside, to journey with me wherever I go.  May your Holy Spirit journey with me as I set out on my journey to Bethlehem this Advent.  Amen.
**  Read
    #+BEGIN_QUOTE
Isaiah 9:1-7
    #+END_QUOTE
**  Reflect
#+BEGIN_QUOTE
What are the special names given to the child who is to be born?
#+END_QUOTE
Wonderful, Counselor, Mighty God, Everlasting Father, Prince of Peace.
**  Apply
#+BEGIN_QUOTE
How is Jesus a "Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace" to you ?  How could he be even more so?
#+END_QUOTE
Because the Hebrew text does not have punctuation, it's hard to know if *Wonderful* should stand on its own or modify *Counselor*.
This passage is many things.  God promises to bring the oppressed out of bondage so they don't feel under the burden of their oppressors as if they live in gloom and walk in the shadow of death.  Jesus brings life.  God is the only one who can give life like this.  That is why the government will be upon the child's shoulders who will act with judgment and justice.

Tonight, as I write amidst the illness of my four-month-old grand niece and interrupted by my daughter's text messages along with my balky voice dictation program on my phone, I long for Jesus to be my Counselor.  I want his ear, his undivided attention.  The peace I seek is not for the world, but for myself and those I love.  I desperately want to believe someone is in charge of my life and of the lives around me.  I want to believe that the one in charge is wonderful, mighty and able to last through all my joys and sorrows.  Jesus is this one.  I just want to be certain of it in my innermost soul.
**  Pray
Dear Jesus, I know you are with me and you care.  I want to have that sense of your caring more acutely.  Amen.
  
* Day 2 (December 1, 2013)
** Pray
Jesus, you are my banner, leading me forward.  Amen.
** Read
#+BEGIN_QUOTE
Isaiah 11:1-10
#+END_QUOTE
** Reflect
#+BEGIN_QUOTE
What will empower this ‚Äúroot of Jesse‚Äù to bring such peace and justice to the world? 
#+END_QUOTE
Fossr the purposes of this guide that I am following, passages from Isaiah are references to the Messiah who is to come.  Reading Jesus back into these texts can be problematic.  Christians have done this for a very long time and continue to do so.  I prefer to take a more Hebrew Scripture centric view so I am a bit in conflict with this guide.  Nevertheless, being present to God's Word and desiring the righteous judgments of this leader, I will agree that Jesus is the one who will bring peace and justice. I can only hope for an earthly leader with such knowledge and wisdom.

To answer the question, the fear of the Lord gives the ruler such wisdom.

When the biblical text speaks of fearing God, it doesn't me that clenching feeling in your gut and the desire to run away.  Jesus often says, "Do not be afraid" and so does the Hebrew Scriptures.  The writer here is speaking of the awesomeness of God, God's wonder and power.  God awes me.  When I am so awed by God's rightness, I want to do everything I can to apply God's wisdom and knowledge to my earthly life.
** Apply
#+BEGIN_QUOTE
What can you do on behalf of peace and justice in your world? Make a plan to start today.
#+END_QUOTE
I spend time every weekday at my local senior center.  I come in contact with a lot of people.  I try to be kind to everyone I meet, to see the good in them and to give them the benefit of the doubt when I can.  World peace and justice is beyond my individual power to influence.
** Pray
Prince of Peace, May my puny efforts at peace and justice be acceptable in your sight.  Show me how I may expand my horizons to live my life more in keeping with your rule.  Amen.
* Day 3 (December 2, 2013)
** Pray
Gracious One, how majestic is your name.  Through your Word, may I come to know your majesty.  Amen.
** Read
#+BEGIN_QUOTE
Isaiah 53:1-6
#+END_QUOTE
** Reflect
#+BEGIN_QUOTE
What was the reason for this  one'sÄôs sorrow and suffering? 
#+END_QUOTE
We despised and rejected him.  We did not find him agreeable because he was not desirable.

Scholars have argued for a long time who this one is and whether this one is Jesus.  The early church saw Jesus in this passage.  Philip and the Ethiopian eunuch discuss this chapter in Acts 8.

Reading it today, I was struck by the fact the "we" were united in despising the one while the "we" went off, each going about his or her own business and leaving the one to sustain the punishment for all.

If our sense of biblical thinking is correct, thinking about individual responsibility begins with the exile to Babylon.  It is likely these words were written during this time frame.  The "we" comes to acknowledge their indebtedness to the one and there is a sense of guilt and horror at what has happened to the one.

The one was so vulnerable.  The one is describe as a tender young shoot.

How often the most vulnerable and least impressive of us suffers and, for the most part, the "we" always ignore them.

** Apply
#+BEGIN_QUOTE
Have you trusted Jesus to take away your "iniquities" ?  Confess any known sin now.
#+END_QUOTE
The sin of ignoring and openly withdrawing from the vulnerable is the sin I will confess today.  Forgive me.
** Pray
Today I pray for all the vulnerable.  Protect them, Lord.  Amen.

* Day 4 (December 3, 2013)
** Pray
All-knowing God, enliven my reflection today with your spirit.
** Read
#+BEGIN_QUOTE
Micah 5:2-5
#+END_QUOTE
** Reflect
#+BEGIN_QUOTE
Where does the prophet say the "promised ruler" will be born?
#+END_QUOTE
The answer, not surprisingly, is Bethlehem.  This is the town where David came from.  This is the place the wise men are told about in Matthew 2.  Neither the Gospel of Mark nor the Gospel of John mention Bethlehem as Jesus' birth place.  In fact, the Gospel of John comments that Jesus was not born in Bethlehem in chapter 6.

What is more interesting to me than the physical birth place is what this "promised ruler" will do.  The ruler receives his strength from God.  He protects the people and welcomes home the faithful remnant.  He provides for the people a safe place in which to live.

When I read a passage like this, I sigh with contentment.  At last!  There will be enough food and security. 

** APPLY
#+BEGIN_QUOTE
What does it mean to you to know Jesus ' birth was planned and foretold by God long in advance?  How might it affect your life today?
#+END_QUOTE
As you may have noticed, I'm squimish about all this emphasis of what has been foretold.  What interests me is God's continuous use of promise.  The prophet spoke of God's desire for them to have strong and effective leadership.  In Jesus, I find this promise fulfilled.
** PRAY
God, I depend on you keeping your promises.  It may take a long time, but you fulfill them.  Amen. 
* Day 5 (December 4, 2013)
** Pray
I look to you, Jesus, as I read my Bible today.  Amen.
** Read
#+BEGIN_QUOTE
Zechariah 9:9-13
#+END_QUOTE
** Reflect
#+BEGIN_QUOTE
What might surprise someone about the description of this king?
#+END_QUOTE
This king rides a donkey.

In the ancient world, this meant the king was not a warrior.  I suspect a king would be ridiculed if he was seen riding a donkey.  What a sissy.

For us, this text points to a ruler who does not embroil his people in war.  Implied is that there is no need.  God has broken the weapons of war, the bow and the horse.  The ruler comes in peace.

If this text sounds familiar, it is used for Palm Sunday when Jesus rode a donkey into Jerusalem.
** Apply
#+BEGIN_QUOTE
Is there anything about Jesus that surprises you? If so, what and why?
#+END_QUOTE


This answer could take a long time to answer and is probably a worthwhile endavor.  For now, let me just say that Jesus kept to his non-violent message and resisted any attempt to be lifted up as a political figure in the ancient world.  Many before him and many after him thought they could change the world through a revolt.  In the end, Jesus overthrew the Roman Empire.
** Pray
Jesus, teach me your way.  May I practice the same kind of humility you did when you rode a donkey into Jerusalem.  Amen.

* Day 6 (December 5, 2013)
** Prayer
Come Holy Spirit.  Amen.
** Read 
#+BEGIN_QUOTE
Galatians 4:4-7
#+END_QUOTE
** Reflect
#+BEGIN_QUOTE
For what reason did God send his son at the right time?
#+END_QUOTE
God sent Jesus to redeem us and make us God's children.
** Apply
#+BEGIN_QUOTE
Recall how God prepared you for the coming of his son into your life. Thank him for that.
#+END_QUOTE
Jesus, you created a longing in me that only you can fulfill. Thank you, Holy One, for drawing me to you.  Amen.
** Pray
Brother Jesus, keep me close as part of the family of God.

