#+Title  The Essential Journey to Bethlehem
#+AUTHOR  Rill
#+EMAIL  rill*at*rillonline.me
* About This Page
November 30 begins Advent in the Christian church.  Some churches focus on Advent while others may only give it passing notice.  I have decided to focus on Advent this year for three reasons:
1.  I am editing an Advent devotional I wrote in 2006.  I hope to post one devotional per day.  You can read it on this blog as well as what I write here.
2.  I will not be at church on the first Sunday of Advent.  I need to take responsibility for my own spiritual journey.
3.  I want to make prayer, Bible reading and reflection and writing about Scripture part of my daily life.
I went in search of a list of daily readings.  The [[http://scriptureunion.org/][Scripture Union/USA]] was one of the web sites I found.  They have a 14-page booklet with a reading guide, prayers, reflection questions and an application section.  I thought it would be a very structured way to go about my own devotions and record them here.  I hope they are useful to both me and you.
* Day 1 (November 30, 2013)
**  Pray
God, you have promised a *paraclete*, one who walks beside, to journey with me wherever I go.  May your Holy Spirit journey with me as I set out on my journey to Bethlehem this Advent.  Amen.
**  Read
Isaiah 9:1-7
**  Reflect
#+BEGIN_QUOTE
What are the special names given to the child who is to be born?
#+END_QUOTE
Wonderful, Counselor, Mighty God, Everlasting Father, Prince of Peace.
**  Apply
#+BEGIN_QUOTE
How is Jesus a "Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace" to you ?  How could he be even more so?
#+END_QUOTE
Because the Hebrew text does not have punctuation, it's hard to know if *Wonderful* should stand on its own or modify *Counselor*.
This passage is many things.  God promises to bring the oppressed out of bondage so they don't feel under the burden of their oppressors as if they live in gloom and walk in the shadow of death.  Jesus brings life.  God is the only one who can give life like this.  That is why the government will be upon the child's shoulders who will act with judgment and justice.

Tonight, as I write amidst the illness of my four-month-old grand niece and interrupted by my daughter's text messages along with my balky voice dictation program on my phone, I long for Jesus to be my Counselor.  I want his ear, his undivided attention.  The peace I seek is not for the world, but for myself and those I love.  I desperately want to believe someone is in charge of my life and of the lives around me.  I want to believe that the one in charge is wonderful, mighty and able to last through all my joys and sorrows.  Jesus is this one.  I just want to be certain of it in my innermost soul.
**  Pray
Dear Jesus, I know you are with me and you care.  I want to have that sense of your caring more acutely.  Amen.
  
* Day 2 (December 1, 2013)
** Pray
Jesus, you are my banner, leading me forward.  Amen.
** Read
#+BEGIN_QUOTE
Isaiah 11:1-10
#+END_QUOTE
** Reflect
#+BEGIN_QUOTE
What will empower this “root of Jesse” to bring such peace and justice to the world? 
#+END_QUOTE
For the purposes of this guide that I am following, passages from Isaiah are references to the Messiah who is to come.  Reading Jesus back into these texts can be problematic.  Christians have done this for a very long time and continue to do so.  I prefer to take a more Hebrew Scripture centric view so I am a bit in conflict with this guide.  Nevertheless, being present to God's Word and desiring the righteous judgments of this leader, I will agree that Jesus is the one who will bring peace and justice. I can only hope for an earthly leader with such knowledge and wisdom.

To answer the question, the fear of the Lord gives the ruler such wisdom.

When the biblical text speaks of fearing God, it doesn't me that clenching feeling in your gut and the desire to run away.  Jesus often says, "Do not be afraid" and so does the Hebrew Scriptures.  The writer here is speaking of the awesomeness of God, God's wonder and power.  God awes me.  When I am so awed by God's rightness, I want to do everything I can to apply God's wisdom and knowledge to my earthly life.
** Apply
#+BEGIN_QUOTE
What can you do on behalf of peace and justice in your world? Make a plan to start today.
#+END_QUOTE
I spend time every weekday at my local senior center.  I come in contact with a lot of people.  I try to be kind to everyone I meet, to see the good in them and to give them the benefit of the doubt when I can.  World peace and justice is beyond my individual power to influence.
** Pray
Prince of Peace, May my puny efforts at peace and justice be acceptable in your sight.  Show me how I may expand my horizons to live my life more in keeping with your rule.  Amen.
