** Author's Note

What follows is a transcript of podcasts I produced in 2006 for Advent.
For the most part, I have not changed anything from what you will hear
if you listen to the audio files. Because I have discontinued my web
sitereferenced in the podcasts, I have updated the transcript with my
current site and contact information. I hope that these writings will be
a blessing to you on your spiritual journey.

I recorded these reflection using the name /Merrill Louise/. It never
stuck.

You can find the /Advent Joy 2006/ page at
[[http://www.archive.org/][archive.org]] page
[[http://www.archive.org/details/advent_joy_2006/][here]]. To download
all the files at once, use any of these links:

[[http://www.archive.org/download/advent_joy_2006/advent_joy_2006_64kb_mp3.zip][Advent
Joy 2006 64kb mp3]]
[[http://www.archive.org/download/advent_joy_2006/advent_joy_2006_64kb.m3u/][Advent
Joy 2006 64kb m3u]]

You may want to edit the /m3u/ file as the reflection for /December
fifth/ is out of order.

Rill July 20, 2013

=[Return to the Table of Contents](index.html)= Introduction
------------

[[http://archive.org/download/advent_joy_2006/advent_joy_2006-29_introduction.mp3/][introduction.mp3]]
from [[http://www.archive.org/][The Internet Archive]]

Advent may be an unfamiliar word to you. It means coming or arrival. It
is the time YOU AND I will set aside during these podcasts to prepare
our hearts and minds for Christmas. In real life, our preparations may
include

-  Shopping for presents for other people,

   -  wrapping them in pretty paper,
   -  tying ribbons and affixing bows;

-  ecorating our home, inside and out,

   -  with colored lights,
   -  scented candles,
   -  garlands,
   -  Santas,
   -  reindeer,
   -  snowmen and women.

-  and special sayings like

   -  Ho! Ho! Ho!
   -  Merry Christmas!
   -  Seasons Greetings!
   -  Happy Holiday!

-  decorating the Christmas tree
-  planning, preparing and making special meals
-  baking cookies and other delectable treats
-  playing OR singingChristmas carols and songs
-  giving and going to parties

The intent of all these activities is joy---the joy of

-  giving and receiving gifts of love
-  sharing good food with good friends and family,
-  celebrating friendship and family ties
-  expressing the hope that the world really can be a place of joy and
   peace.

Sadly, we know our preparations often fall short of our expectations of
ourselves, of others and the season. We work ourselves into a frenzy out
of a sense of duty rather than joy. We spend more than we have. We get
stressed out. We snap at family members, coworkers and friends. We feel
rushed, panicked that everything will not be perfect or even get done.
We feel lonely. There is something missing. We don't feel as happy as we
think other people are. We despair. We think there is something wrong
with us because the so- called spirit of Christmas hasn't touched us --
our souls.

Real life spirituality acknowledges all the healthy ways you and I
prepare for Christmas. Presents are wonderful. Christmas cookies taste
delicious. Decorations enhance our living and working spaces.

Each year, for the four weeks preceding Christmas, the season of Advent
invites you and me to take a few minutes every day

-  to open ourselves to God
-  to reflect on Jesus' birth, its meaning for and impact on us
-  to respond to God with love and joy

I hope these short reflections, inspired by the
[[http://www.americanbible.org/][American Bible Society]]'s daily
readings for November 30-December 25, 2006 will bring Advent Joy in your
heart, joy that you can share with others and with God as your
relationship with God grows deeper in joy this Advent season.

** A Word about These Podcasts

Each podcast will begin with a quotation from the Contemporary English
Version of the Bible. These quotations will be a portion of a longer
reading which I will announce. I hope you will find time during the day
to read or listen to this longer passage. After I read the Scripture
quotation, I will reflect on it, speaking about how it helps us prepare
for Jesus' arrival at Christmas. I will conclude each reflection with a
very short prayer.

I am making these podcasts available at no charge. his work is licensed
under a Creative Commons Attribution-NonCommercial-NoDerivs 2.5 License.
You can listen to them and share them with friends. You cannot sell them
or modify them. Advent Joy 2006 is a presentation of Living in the
Wilderness Media. further information, go to the Advent Joy 2006 page at
at send comments to me via the Contact Me page.

=[Return to Index](index.html)=

** CALL TO ACTION

Thursday, November 30, 2006

The reading is Psalm 150.

#+BEGIN_QUOTE
  Praise our God! His deeds are wonderful, too marvelous to describe.
  (v. 2)
#+END_QUOTE

How do you go about preparing for Christmas in real life? You may be
beginning by making a list

-  going to the store to browse
-  doing a web search
-  asking** advice
-  checking on what you already have on hand

Spiritual preparations for an event are no different. Psalm 150 calls us
to action, too. Let me list the activities. * shouting * dancing *
strumming * plucking * blowing * clashing

It's all quite noisy. It's all quite different from hushed worshippers
engaging in solemn introspection. Self-examination is a useful activity.
Nevertheless, Psalm 150 invites us to loud and showy praise of our God
en lieu of lengthy descriptions of all God's marvelous deeds.

So * crank up the music if you're not wearing ear buds. * Grab that
sweatshirt with the words Joy! JOY! JOY! Written across your chest *
Swing your hips. * Get a bounce in your step. * Sing along with the
in-store carols. * Smile. * And if you're up to it, a few Ho! Ho! Ho!'S
won't hurt anybody.

You're not crazy. You're praising God with your whole self and sharing
your joy with everybody around you.

Let us pray ... Wonderful God, may my praise of you be rambunctious and
contagious today. Amen.

=[Return to the Table of Contents](index.html)=
