#+TITLE: In Which I Meet Kearsarge
#+AUTHOR: Rill Online
#+HTML_LINK_HOME: https://rillonline.github.io 
#+HTML_LINK_UP: [[file:index.org][Kearsarge]]
#+KEYWORDS: Ronnie Camberwell
#+KEYWORDS: Captain Star Runner
#+KEYWORDS: mystery
#+KEYWORDS: science fiction

#####

* In Which  I Meet Kearsarge

People are lining up outside the Galactic Diner, waiting for a table
inside. I am shocked. I have never seen the restaurant so busy. The
people are dressed in sporting clothes--I mean they look like cyclists,
runners, equestrians, space travelers from a bygone era. What is this?

Then I remember. The League of the Solar Planets Olympics is about
to begin in Ptolemy City. Fans always dress as participants for their
favorite events.

"Well," I thought. "I will never get a seat inside. Besides, the Galactic
Diner has a lot of memories for me and I am trying to put the last
several years behind me.Â 

Well, then, where should I go for some breakfast?

I start walking along the Valley of Kings, making my way toward Lower
Nile Street and the meaner streets of the city. With all these tourists in
town, all the nicer places will also be overcrowded. I want an affordable
restaurant and some place I can make my own.

"Detective Camberwell," someone calls.

I keep walking. I am no longer a police detective. I do not have to talk
to anyone about my former life.

I hear footsteps running behind me. Reluctantly, I turn around. This
person could be dangerous. This is, after all, Ptolemy City. I want to
be certain. no one wants me dead. Besides, I may know them and I do not
want to be rude.

"Detective Camberwell," the woman says again, running toward me.

She is a large woman. She is not dressed for the games and I have never
seen her before.

"I need to speak with you," she says, coming to a stop in front of me.

She is panting though judging from my brief observation of her running,
she is used to working out. She is not graceful. She is powerful and
well muscled. Personally, I like my women more delicate and fluid,
but damn!! I find her quite attractive.

"I am not a detective," I say. "I haven't been on the force in years. I
am afraid I can't help you with any legal matters."

"I know you're not a detective any more," the woman says. "I just didn't
know what else to call you. I need to speak with you. Can we go somewhere
to talk."

And so my encounter with Kearsarge began.

Kearsarge, she never offered me any more identification than that, knew
of a small place off Lower Nile Street. Only a few customers sat at the
dozen tables and occupied a couple of stools at the counter. The woman
behind the counter calledÂ  Kearsarge by name by which I deduced she
was a regular. This was not brilliant detecting on my part. The woman
called everyone by name. She asked me what mine was.

"Ronnie," I said.

"And what will you have, Ronnie?" the woman asked.

My second shock of the day. Here was a human being asking me for my
order. No automated tables here. No menu display to tap or stare at. I
located a renewable writing surface behind the woman with today's
offerings. She even could serve me meat if I wanted to eat it which I
did not.

Kearsarge did not order except to confirm she wanted the usual.

Kearsarge selected the table in the corner in the back where we would
have relative privacy.

"What is this about?" I asked when we were seated.

Kearsarge took a long sip of her very hot coffee before speaking.

"I'm getting messages from a dead person," she said. "I want you to find
out who is sending them and stop them."

"Why not just mark them as Spam and block the sender?" I said.

Getting unwanted messages is a nuisance but there are easy ways not to
be bothered by them. Every child knows how to do this. Kearsarge hardly
needed to chase me down the street and bring me to her regular eating
establishment to ask me about this.

"I tried," Kearsarge said. "I couldn't stop them."

I sipped my tea. For a nondescript place, they brewed a wicked cup of
tea. None of this was making any sense.

"There's more to this story," I finally said.

"Yes,' Kearsarge said. "That's why I want to hire you."

"Hire me?" I asked.

"Yes," Kearsarge said. "I wouldn't expect you to work for free. You are
an investigator, right?"

"I didn't think so," I said.

"Troy Camberwell said you were a good investigator." Kearsarge persisted.

Thanks, Dad.

"Yes," I replied with a great deal of caution. "I am. But I'm not on
the police force any more."

Our food arrived and for a time we sat in silence eating. The food was
excellent. I hoped it would not be awkward for me to come here
again. Kearsarge only nimbled at a piece of toast while I dug into my
huevos rancheros with gusto. I was surprisingly hungry.

"I really need your help," Kearsarge said after our plates were cleared
and we each had a fresh cup before us to drink. "I'm scared."

I saw how her hands trembled as she picked up her coffee cup to
drink. Being a large woman with a lot of confidence her admission
surprised me. Perhaps I had allowed her size and assured manner in
approaching a stranger and conducting her to her favorite eating
establishment to deceive me.

"Scared of what?" I asked. Damn! My old instincts to protect and
defend the weak and defenseless came to the forefront of my mind.

"The dead man was my husband," Kearsarge said. She looked away. "He was
violent."

"And now he's dead," I said.

"That's right," Kearsarge said.

"You're certain about this?"

Death is a fluid thing in Ptolemy City. You heard people were dead and
then you met them on the street the next day. There was nothing
miraculous in this. They were hiding from someone. They were scamming
someone. They were trying to get out of a contract or collect part of
the money from a contract put out on them. After all, assassination is
legal here. It requires a contractual agreement, notice and an
assassin. Murder, on the other hand, is another matter. In some
circumstances, it can be prosecuted.

"Yes," Kearsarge said. "I had him assassinated."

"You had proof then."

The nature of the proof varies, but it always is provided. Sometimes
it is the body, a certified video of the killing, noterized statements
from witnesses. Proof is part of the standard assassination contract.

"Yes. The contract was executed properly and I paid."

"But he's alive."

"No. I'm certain of that. It's just--" And here Kearsarge looked away
again.

What wasn't she telling me.

"What aren't you telling me?" I said aloud. My patience was beginning
to wear thin. Protect and defend had its limits. I was being toyed
with.

"There's a service," Kearsarge said, still not looking at me. "You can
send messages to your loved ones after you are dead. There's nothing
magical about them. You write them all before you die. You can send
them on birthdays and anniversaries--that sort of thing. They're meant
to be comforting. But these messages--"

And here she visibly shivered.

"These messages are about my death--a horrible death."

Tears began to trickle down her face.

"I think it will happen--and very soon. I want you to stop it."

I refrained from answering Kearsarge right away. Clearly, she believed
everything she had told me. The messages were probably real, too. I
did not think Kearsarge was experiencing any remorse for her husband's
death.

"I can pay you," Kearsarge said. She must haveÂ  interpreted my
silence as refusal.

"Payment isn't the point," I said. "Your safety is. You need to go to
a shelter."

"A shelter?"

"For victims of domestic violence."

"I can take care of myself," Kearsarge answered immediately.

"Which is it?" I asked. "You're asking me to keep you from being
killed on the one hand and on the other you are claiming you can take
care of yourself."

"I just want you to stop the messages," Kearsarge said. "that's
all. I'm not asking you to protect me in any way. I can take care of
myself"

"And you think that if I can stop the messages you'll be safe? That
makes no sense."

"My safety isn't the issue here," Kearsarge said. She was becoming
impatient and her tone suggested she thought I was being quite
obdurate.

"I disagree," I said, getting to my feet. "Thank you for breakfast."

I walked out of the restaurant  without  a backward glance. I strode away,
determined not to be called back. I couldn't help someone who didn't
want to be helped. 

The next time I saw Kearsarge, she was dead.

