#+AUTHOR: Rill Online
#+OPTIONS: html-postamble:nil

T
Keywords to include:

- science fiction
- well-plotted
- speculative fiction
- strong women
- space
- mystery
- other worlds
- aliens
- private investigator
- romance
- debut novela

- in this well-plotted debut novela by Rill.


#+begin_center
*Coming Soon to this page!*

You'll download it here!
#+end_center
- well-plotted debut novella
- suspenseful speculative fiction mystery that will keep you reading until the very last page
This science fiction novella set in the Pharaoh Star System has it all:
  - strong female characters
    * the Czarina :: the canny gossip blogger
    * Kearsarge :: The wealthy marathon runner who will stop at nothing to get what she wants, even sharing the location of her favorite Lower Nile Street diner.
    * Tara Lee :: the alluring Alexandria Space Station manager
    * Ronnie Camberwell ::heartsick, reluctant investigator who just
      solve the mystery of the messages from the dead.


  - human settlements in hostile environments   
    * Ptolemy City :: Its transparent dome showcases Hypatia's toxic
                      and unearthly-colored atmosphere
    * Over the Moon :: the League of Hypatian Pirates operates its
                       spaceport, casinos and many fine-dining establishments bbon
                       Cleopatra, one of Hypatia's two moons
  - Romance:
    
    Who wants Ronnie and who does she want? The Czarina has much to
    blog about but will she?

   
  - from Over the Moon spaceport operated by the League of Hypatian
  Pirates to the unscrupulous upper class of Ptolemy City
* 
* Tara Leigh
