#+OPTIONS: html-postamble:nil

in this well-plotted debut novela by Rill suspenseful speculative
fiction mystery that will keep you reading until the very last page
This well-plotted speculative fiction novella set in the Pharaoh Star System has it all:
  - strong female characters
    * the Czarina :: the canny gossip blogger
    * Kearsarge :: The wealthy marathon runner who will stop at nothing to get what she wants, even sharing the location of her favorite Lower Nile Street diner.
    * Tara Lee :: the alluring Alexandria Space Station manager
    * Ronnie Camberwell ::heartsick, reluctant investigator who just
      wants to solve the mystery of the messages from the dead.
  - human settlements in hostile environments   
    * Ptolemy City :: Its transparent dome showcases Hypatia's toxic
                      and unearthly-colored atmosphere
    * Over the Moon :: the League of Hypatian Pirates operates its
                       spaceport, casinos and many dining
                       establishments from the greasy spoons on its
                       lowest level to the elegant Cat and the Fiddle
                       and the boisterous Hey Diddle Diddle at the
                       top. Its worth a trip to Cleopatra, one of Hypatia's two moons
  - Romance:
    
    Who wants Ronnie and who does she want? The Czarina has much to
    blog about but will she?

  - Money:

    Who has it? Who wants it and what will any of Ptolemy City's rich
    and unscrupulous movers and shakers do or say to get or keep it?

#+begin_center
*Coming Soon to this page!*

You'll download it here!
#+end_center
