#+TITLE: On Editing
#+AUTHOR: Rill
#+DATE: 2014-02-20
I am slowly, and I mean slowly, trying to go through Star Runner's first adventure.  It is very boring.  The ideas are there.  The execution is dreadful.

In reading Rochelle's post on [[http://www.writenowcoach.com/blog/?p%3D2276][Stuck? Write Out of Order]] it occurs to me that I can work on my outline out of order.  I need to take a chapter, any chapter, and summarize it.  If I do this, I will eventually get them all done.  I won't be so distressed about the writing.  The outline is only a list of ideas.

When I read the unfinished manuscript through and as I reread chapters in order to outline them I am discovering what this novela is about.  I thought I was writing a space adventure.  The space adventure is there, but the story of Star's friendship with Tamara is there, too.  They are two individuals who have been cut loose from life as they knew it.  They are trying to find their way and having a rough go at it.  This is also a story about not fitting in and seeking acceptance.

I have come to understand more clearly how naive and vulnerable Star is.  I am also getting a better understanding about Gyllian and Star's relationship.  Gyllian is mentor and protector.  I didn't know that until I reread the story seven years later and tried to think of what to do with the gaping plot holes.

I've been able to do a fair amount of trimming.  When I finish the outline, I fully expect to do more before I start in on the rewrite.  This does not need to be a novel-length story.  A novelette to novela length will be just fine.
 
