# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rill Online
tagline: Where all my writing lives...
description: >- # this means to ignore newlines until "baseurl:"
  Rill Online's blog and web Site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rillonline.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty 

# Build settings
markdown: kramdown
markdown_ext: "kd,kramdown,md,mk,markdown"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# excludes
exclude:
   - bits-and-pieces

paginate: 1            

# List of pages that should be included in the masthead
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
